name: Lint when to request merge to master branch
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install with package.json
        run: yarn install --ignore-scripts
      - name: Lint markdown
        run: yarn run markdownlint ./articles/*.md